### ISSUE TITLE
Not possible to add middleware via config/initializers/omniauth

### ISSUE THREAD

**Issue by amseledka** [andrewvanbeek-okta/omniauth-oktaoauth#2]
In https://github.com/dandrews/omniauth-okta it's possible to add `:okta` provider to `config/initializers/omniauth.rb`

but in this gem the only way is to add auth via devise, right?

**Comment by EvanGranthamBrown** [comment]
Seconded on this issue. Devise comes with a lot of baggage (e.g., it requires an ORM and has to be integrated into the user model) and I don't see that it brings much to the table. Most of what you'd want Devise for - password management, registering new users, etc. - is already handled by Okta.

**Comment by andrewvanbeek-okta** [comment]
@amseledka, @EvanGranthamBrown. The readme is a little misleading so the example talks to interacting with a devise app, but at the end of the day it is an omniauth strategy so it should be able to just interact with omniauth in the omniauth.rb initializer.
